name: Build & Deploy Algorithms RAU

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

#      - name: Install python packages
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#
#      - name: Run Unit Tests
#        run: pytest homework6/test_hom1.py --maxfail=1 --disable-warnings

        # Check for changes in homework folders
      - name: Check for changes in homework folders
        id: check-changes
        run: |
          modified_homeworks=""
          
          for i in {1..9}; do
            files_changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^homework$i/")
            if [[ -n "$files_changed" ]]; then
              modified_homeworks="$modified_homeworks homework$i"
            fi
          done
          
          echo "Modified homework folders: $modified_homeworks"
          
          echo "modified_homeworks=$modified_homeworks" >> $GITHUB_ENV

      # Run tests for the modified homework folders
      - name: Run tests for modified homework folders
        run: |
          for homework in ${{ env.modified_homeworks }}; do
            echo "Running tests for $homework..."
            cd $homework
            pytest test_hom1.py --maxfail=1 --disable-warnings
          done
