name: Build & Deploy Algorithms RAU

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Run unit tests
#        run: |
#          pytest -v --capture=no homework6/test_hom1.py --maxfail=1 --disable-warnings

      - name: Run tests for modified files
        run: |
          echo "Checking for modified files..."
          files_changed=$(git diff --name-only HEAD^ HEAD)
          echo "Files changed: $files_changed"
          
          export PYTHONPATH=$(pwd)/src:$PYTHONPATH
          
          for file in $files_changed; do
            if [[ $file == src/homework6/* ]]; then
              pytest -v --capture=no tests/homework6/ --maxfail=1 --disable-warnings
            fi
            if [[ $file == src/homework5/* ]]; then
              pytest -v --capture=no tests/homework5/ --maxfail=1 --disable-warnings
            fi
          done    
